### ISSUE TITLE
https://www.w3.org/TR/perf-timing-primer/ leads to 404

### ISSUE THREAD

**Issue by lmedini** [w3c/perf-timing-primer#7]
Hi all,

Just to mention that the "official" URI of the latest published version<https://www.w3.org/TR/perf-timing-primer/> is currently not reachable.

Thanks for the great work.

Lionel Médini.

**Comment by igrigorik** [comment]
Hmm.. @plehegar @siusin is it meant to be on w3.org? We have it on https://w3c.github.io/perf-timing-primer/, which is where I personally tend to point everyone.

**Comment by siusin** [comment]
Indeed. This document was merely a note to help people understand those various timing APIs, so I think it makes sense it keep as it is :)

**Comment by alundiak** [comment]
I confirm, the url https://www.w3.org/TR/perf-timing-primer/ - 404, and if this issue is not relevant anymore, I would suggest to close, or if someone have access to w3.org - fix it.

**Comment by siusin** [comment]
Thanks @alundiak and @lmedini . The /TR latest version link has been remove.

The group is making great progress on [performance timing](https://docs.google.com/spreadsheets/d/e/2PACX-1vQAriyZXd_UfwJ0ptBlGn4qp7rSIa1u5yiaHKthOVSHuXE4bwheTS3EXgUcu5308PIsii5la6PEll9Z/pubhtml?gid=0&single=true) monitoring these days, please also look at [Performance Observer](https://w3c.github.io/performance-timeline/#the-performanceobserver-interface), [Long Tasks](https://github.com/w3c/longtasks) and [Paint Timing](https://github.com/w3c/paint-timing) if you are interested in Perf-Timing. Sorry I haven't got the time to update the primer yet.
